name: fitwise
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  crypto: ^3.0.3
  provider: ^6.1.1
  cupertino_icons: ^1.0.8
  audioplayers: ^6.0.0   # ğŸµ for alarm sound
  intl: ^0.18.0
  video_player: ^2.9.1
  video_player_web: ^2.3.5


dependency_overrides:
  video_player_web: 2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/sounds/alarm.mp3   # ğŸµ alarm sound
    - assets/male_exercises/
    - assets/female_exercises/
